### ISSUE TITLE
How to cross-compile?

### ISSUE THREAD

**Issue by weichihl** [awslabs/aws-crt-python#346]
Hi, I want to cross-compile the CRT Python, but I'm unsure how to do that. Is there a way to pass variables and set `CMAKE_TOOLCHAIN_FILE` for CMake configuration to configure all cross-compile things? Thanks.

**Comment by graebm** [comment]
Cross-compiling isn't officially support for aws-crt-python.

If you're asking because you need wheels that work on Apple silicon, that's fixed. As of v0.13.11 the `universal2` wheels for Python 3.9+ will work on either Intel or Apple silicon

The way we do it when creating wheels for [multiple platforms](https://pypi.org/project/awscrt/#files), is to just build the wheel on that platform/architecture. Either we use the [manylinux](https://github.com/pypa/manylinux#docker-images) docker images, or we build on an actual Windows or macOS machine. If you need to compile for a platform that we're not covering, you'll need to build on that platform (or a docker image of that platform).

I don't personally know how one would go about cross-compiling a python C extension, since `setuptools` controls so much about how C extensions are compiled, which seems to always target the current Python installation, getting its info from [sysconfig](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform).
